name: presto_app
description: Prest'o app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 
  google_sign_in: 
  sign_in_with_apple:
  http: ^1.2.2 
  

  cupertino_icons: ^1.0.8

  # ðŸ”¥ Firebase / Firestore / URL launcher
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  cloud_functions: ^5.0.0
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.10
  speech_to_text: ^6.6.0
  record: ^5.0.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/chrono_1min.png
    - assets/images/
    - assets/data/cities/
    - assets/data/cities_compact.json